### ISSUE TITLE
API Server

### ISSUE THREAD

**Issue by ghost** [ontopapp/ontop-push#1]
Can you release API server code so we can self-host and hit our own API server?

**Comment by poya-r** [comment]
Hey the API is part of a whole platform including user/app management and it'll requires the db schema and the app source itself to make it work but the push part is based on the AWS' SNS service. This tutorial should give you the basics to setup your own web-to-android push using GCM.
http://docs.aws.amazon.com/sns/latest/dg/mobile-push-gcm.html

hope this helps.
